document.writeln("    <div id=\"headNav\" class=\"bg_f5 col_67 hidden-xs bor_b_e3\">");
document.writeln("      <div class=\"container size12\">");
document.writeln("        <div class=\"row\">");
document.writeln("          <div class=\"pull-left\">HI , 欢迎来齐鲁艺票通</div>");
document.writeln("          <div class=\"pull-left\">[");
document.writeln("            <a href=\"./login.html\" class=\"inlineb login_a col_red\">登陆</a>");
document.writeln("            <a href=\"./registered.html\" class=\"inlineb col_67\">注册</a> ]");
document.writeln("          </div>");
document.writeln("          <a href=\"#\" class=\"pull-left ml3\">");
document.writeln("            <span class=\"verticalBar\">|</span>我的艺票通");
document.writeln("            <img src=\"../img/dropDown.png\" class=\"my_dropdown_i\" alt=\"\">");
document.writeln("            <span class=\"verticalBar\">|</span>");
document.writeln("          </a>");
document.writeln("          <a href=\"./mine/order-mineRecen.html\" class=\"pull-left ml3\">我的订单</a>");
document.writeln("          <div class=\"pull-right\">");
document.writeln("            <a href=\"./nav-right/weixin.html\" class=\"pull-left\">齐鲁艺票通微信</a>");
document.writeln("            <span class=\"pull-left verticalBar\">|</span>");
document.writeln("            <a href=\"./nav-right/phone.html\" class=\"pull-left\">手机版</a>");
document.writeln("            <span class=\"pull-left verticalBar\">|</span>");
document.writeln("            <a href=\"./nav-right/customer-service.html\" class=\"pull-left\">客户服务");
document.writeln("              <img src=\"../img/dropDown.png\" class=\"my_dropdown_i\" alt=\"\">");
document.writeln("            </a>");
document.writeln("            <span class=\"pull-left verticalBar\">|</span>");
document.writeln("            <a href=\"./nav-right/navigation.html\" class=\"pull-left\">网站导航");
document.writeln("              <img src=\"../img/dropDown.png\" class=\"my_dropdown_i\" alt=\"\">");
document.writeln("            </a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div id=\"headSearch\" class=\"col_67 row\">");
document.writeln("      <div class=\"container size12\">");
document.writeln("        <div class=\"row bg_ff\">");
document.writeln("          <div class=\"col-sm-3 overflow hidden-xs p0\">");
document.writeln("            <div class=\"pull-left col-xs-8 col-sm-12 col-sm-offset-0\">");
document.writeln("              <img src=\"../img/logo.png\" alt=\"\" id=\"logo\" class=\"pull-left col-xs-6 hidden-xs p0\">");
document.writeln("              <img src=\"../img/logo2.png\" alt=\"\" id=\"logo-xs\" class=\"pull-left col-xs-8 hidden-lg hidden-md hidden-sm p0\">");
document.writeln("              <div class=\"pull-left location\">");
document.writeln("                <img src=\"../img/location.png\" alt=\"\">");
document.writeln("                <span class=\"col_71\">济南</span>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\"col-sm-6\">");
document.writeln("            <div class=\"col-sm-12 p_b10 row\">");
document.writeln("              <div class=\"inputBox pull-right col-xs-12\">");
document.writeln("                <div class=\"row\">");
document.writeln("                  <div class=\"col-xs-1 p0\">");
document.writeln("                    <img src=\"../img/glass.png\" class=\"p0 glass\" alt=\"\">");
document.writeln("                  </div>");
document.writeln("                  <div class=\"col-xs-9 p0\">");
document.writeln("                    <input type=\"text\" class=\"col-xs-12 p0\" placeholder=\"请输入演出/艺人/场馆名称\">");
document.writeln("                  </div>");
document.writeln("                  <div class=\"col-xs-2 bg_red col_ff pull-right text-center size17 p0 searchBtn\">搜索</div>");
document.writeln("                </div>");
document.writeln("                <div class=\"row hidden-xs\">");
document.writeln("                  <ul class=\"recommend overflow\">");
document.writeln("                    <li class=\"pull-left\">");
document.writeln("                      <a href=\"#\" class=\"col_b4\">儿童剧</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"pull-left\">");
document.writeln("                      <a href=\"#\" class=\"col_b4\">音乐会</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"pull-left\">");
document.writeln("                      <a href=\"#\" class=\"col_b4\">皇家马戏杂技</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"pull-left\">");
document.writeln("                      <a href=\"#\" class=\"col_b4\">历山艺享汇</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"pull-left\">");
document.writeln("                      <a href=\"#\" class=\"col_b4\">张尊莲</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\"col-sm-3 size13 phone hidden-xs text-right col_67\">");
document.writeln("            <div class=\"row\">咨询热线：400-0099-566</div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");

document.writeln(" <div class=\"col-xs-12 bg_ff p0 pos_rel bor_b_e3 \">");
document.writeln("      <div class=\"container p0 search\">");
document.writeln("        <div id=\"mainNav\" class=\"clearfix\">");
document.writeln("          <ul class=\"col-sm-7 pos_sta text-center p0 size16 hidden-xs\">");
document.writeln("            <li class=\"col-sm-2\">");
document.writeln("              <a href=\"index.html\" class=\"\">首页</a>");
document.writeln("            </li>");
document.writeln("            <li class=\"col-sm-2 pos_sta\" id=\"playInfo\">");
document.writeln("              <a href=\"show-info.html\" class=\"col_00\">演出信息");
document.writeln("                <img src=\"../img/dropDown.png\" alt=\"\">");
document.writeln("              </a>");
document.writeln("              <div class=\"overflow size14 col-sm-12 pos_abs col_00 hidden-xs p0 bg_ff infoBox\">");
document.writeln("                <ul class=\"container overflow\">");
document.writeln("                  <li>");
document.writeln("                    <a href=\"show-info.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i1.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i1a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>话剧歌剧</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"showInfo.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i2.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i2a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>音乐会</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"showInfo.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i3.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i3a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>舞蹈</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"showInfo.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i4.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i4a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>曲艺</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"showInfo.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i5.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i5a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>体育</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"showInfo.html\" class=\"text-center col-sm-12\">");
document.writeln("                      <img src=\"../img/nav_i6.png\" class=\"nav_i_a\" alt=\"\">");
document.writeln("                      <img src=\"../img/nav_i6a.png\" alt=\"\" class=\"nav_i_b\">");
document.writeln("                      <div>儿童剧</div>");
document.writeln("                    </a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("            </li>");
document.writeln("            <li class=\"col-sm-2\">");
document.writeln("              <a href=\"./news-update.html\" class=\"col_00\">新闻动态</a>");
document.writeln("            </li>");
document.writeln("            <li class=\"col-sm-2\">");
document.writeln("              <a href=\"./yuanxian-introduced.html\" class=\"col_00\">院线介绍</a>");
document.writeln("            </li>");
document.writeln("            <li class=\"col-sm-2\">");
document.writeln("              <a href=\"./guanyu.html\" class=\"col_00\">关于本站</a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("          <nav class=\"navbar navbar-fixed-top hidden-lg hidden-md hidden-sm navbar-default\">");
document.writeln("            <div class=\"container-fluid\">");
document.writeln("              <div class=\"navbar-header\">");
document.writeln("                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"");
document.writeln("                  aria-controls=\"navbar\">");
document.writeln("                  <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("                  <span class=\"icon-bar\"></span>");
document.writeln("                  <span class=\"icon-bar\"></span>");
document.writeln("                  <span class=\"icon-bar\"></span>");
document.writeln("                </button>");
document.writeln("                <a class=\"navbar-brand col-xs-9 p0 size12\" href=\"#\">");
document.writeln("                  <div class=\"pull-left col-xs-12 col-sm-offset-0\">");
document.writeln("                    <img src=\"../img/logo.png\" alt=\"\" id=\"logo\" class=\"pull-left col-xs-6 hidden-xs hidden-sm hidden-md p0\">");
document.writeln("                    <img src=\"../img/logo2.png\" alt=\"\" id=\"logo-xs\" class=\"pull-left col-xs-7 col-sm-11 hidden-lg p0\">");
document.writeln("                    <div class=\"pull-left hidden-md hidden-sm location\">");
document.writeln("                      <img src=\"../img/location.png\" alt=\"\">");
document.writeln("                      <span class=\"col_71\">济南</span>");
document.writeln("                    </div>");
document.writeln("                  </div>");
document.writeln("                </a>");
document.writeln("              </div>");
document.writeln("              <div id=\"navbar\" class=\"navbar-collapse bg_f8 collapse\">");
document.writeln("                <ul class=\"nav navbar-nav size12\">");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">登录</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">注册</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">首页</a>");
document.writeln("                  </li>");
document.writeln("                  <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">演出信息");
document.writeln("                      <span class=\"caret\"></span>");
document.writeln("                    </a>");
document.writeln("                    <ul class=\"dropdown-menu size12\">");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">话剧歌剧</a>");
document.writeln("                      </li>");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">音乐会</a>");
document.writeln("                      </li>");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">舞蹈</a>");
document.writeln("                      </li>");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">曲艺</a>");
document.writeln("                      </li>");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">体育</a>");
document.writeln("                      </li>");
document.writeln("                      <li>");
document.writeln("                        <a href=\"#\">儿童剧</a>");
document.writeln("                      </li>");
document.writeln("                    </ul>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">新闻动态</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">院线动态</a>");
document.writeln("                  </li>");
document.writeln("                  <li>");
document.writeln("                    <a href=\"#\">关于本站</a>");
document.writeln("                  </li>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </nav>");
document.writeln("          <div class=\"col-sm-offset-2 hidden-xs col-sm-3 p0\">");
document.writeln("            <div class=\"text-right\">");
document.writeln("              <a href=\"#\" class=\"col-sm-5 col-sm-offset-1 p0 size22\">");
document.writeln("                <img src=\"../img/theater.png\" alt=\"\">");
document.writeln("                <b class=\"col_red\">场馆库</b>");
document.writeln("              </a>");
document.writeln("              <a href=\"huimin-show.html\" class=\"col-sm-6 col_red p0 size22\">");
document.writeln("                <img src=\"../img/ticket.png\" alt=\"\">");
document.writeln("                <b class=\"col_red\">惠民演出</b>");
document.writeln("              </a>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"clearfix\"></div>");