document.writeln("<div class=\" hidden-xs p0 p_t30 clearfix\">");
document.writeln("      <div class=\"container bor_b_e3 col_67 p0 bor_t_e3 hidden-xs\" id=\"guide\">");
document.writeln("        <div class=\"col-md-2 section\">");
document.writeln("          <div class=\"left pull-left\">");
document.writeln("            <img src=\"../../img/buyTicket.png\" alt=\"\">");
document.writeln("          </div>");
document.writeln("          <div class=\"pull-left right\">");
document.writeln("            <div class=\"size14 col_00\">购票指南</div>");
document.writeln("            <a href=\"../../html/guide/tickets-process.html\" class=\"size14\">购票流程</a>");
document.writeln("            <a href=\"../../html/guide/tickets-book.html\" class=\"size14\">预定说明</a>");
document.writeln("            <a href=\"../../html/guide/tickets-return.html\" class=\"size14\">退换及缺货说明</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"col-md-2 section\">");
document.writeln("          <div class=\"left pull-left\">");
document.writeln("            <img src=\"../../img/buyTicket2.png\" alt=\"\">");
document.writeln("          </div>");
document.writeln("          <div class=\"pull-left right\">");
document.writeln("            <div class=\"size14 col_00\">订票方式</div>");
document.writeln("            <a href=\"../../html/guide/booking-phone.html\" class=\"size14\">电话订票</a>");
document.writeln("            <a href=\"../../html/guide/booking-online.html\" class=\"size14\">在线订票</a>");
document.writeln("            <a href=\"../../html/guide/booking-door.html\" class=\"size14\">上门购票</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"col-md-2 section\">");
document.writeln("          <div class=\"left pull-left\">");
document.writeln("            <img src=\"../../img/shopcar.png\" alt=\"\">");
document.writeln("          </div>");
document.writeln("          <div class=\"pull-left right\">");
document.writeln("            <div class=\"size14 col_00\">配送说明</div>");
document.writeln("            <a href=\"../../html/guide/send-himself.html\" class=\"size14\">送货上门</a>");
document.writeln("            <a href=\"../../html/guide/send-door.html\" class=\"size14\">上门自取</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"col-md-2 section\">");
document.writeln("          <div class=\"left pull-left\">");
document.writeln("            <img src=\"../../img/money.png\" alt=\"\">");
document.writeln("          </div>");
document.writeln("          <div class=\"pull-left right\">");
document.writeln("            <div class=\"size14 col_00\">付款方式</div>");
document.writeln("            <a href=\"../../html/guide/pay-online.html\" class=\"size14\">在线支付</a>");
document.writeln("            <a href=\"../../html/guide/pay-phone.html\" class=\"size14\">电话支付</a>");
document.writeln("            <a href=\"../../html/guide/pay-goodsTo.html\" class=\"size14\">货到付款</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"col-md-2 section\">");
document.writeln("          <div class=\"left pull-left\">");
document.writeln("            <img src=\"../../img/heart.png\" alt=\"\">");
document.writeln("          </div>");
document.writeln("          <div class=\"pull-left right\">");
document.writeln("            <div class=\"size14 col_00\">特色服务</div>");
document.writeln("            <a href=\"../../html/guide/teSe-huiMin.html\" class=\"size14\">惠民演出</a>");
document.writeln("            <a href=\"../../html/guide/teSe-venues.html\" class=\"size14\">场馆库</a>");
document.writeln("            <a href=\"../../html/guide/teSe- member.html\" class=\"size14\">艺票通会员</a>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <!-- 指南结束 -->");
document.writeln("    <!-- 友情链接开始 -->");
document.writeln("<div class=\"col-sm-12 hidden-xs p0 bg_ff overflow\">");
document.writeln("      <div class=\"container hidden-xs overflow\" id=\"link\">");
document.writeln("        <ul class=\"clearfix\">");
document.writeln("                  <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.mcprc.gov.cn/\"><img src=\"../../img/a106748911e603dfeeef4e95909d3057.jpg\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"中华人民共和国文化部\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdwht.gov.cn/\"><img src=\"../../img/abc36bae83faba90d3b91deb9054d7e0.png\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东省文化厅\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdpag.com/\"><img src=\"../../img/a0fa60ad3b64925d597997959425d2fb.jpg\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东演艺集团\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.jsyanyi.cn/\"><img src=\"../../img/6ad87c504d1fc65f4bbbb1310c0c8ad2.jpg\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"江苏省演艺集团\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.qaf.org.tw/\"><img src=\"../../img/b6362cb6f9686e8360769479a0007915.jpg\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"广艺基金会\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://culture.dzwww.com/\"><img src=\"../../img/83f972b351da942597bbab5353730878.gif\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东文化历史\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdmuseum.com/\"><img src=\"../../img/49fc67503fbbc4692e027ec56485c306.png\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东博物馆\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.ccdy.cn/\"><img src=\"../../img/09a778bb13a239f7c3585cdb8cb1047c.gif\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"中国文化传媒网\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdcbcm.com/\"><img src=\"../../img/deb8209320b64417d07338c84c99d920.png\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东出版传媒股份有限公司\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sddjy.org/index.html\"><img src=\"../../img/275ae54ed30e1b3c13f19e0d7885b99d.png\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东省会大剧院\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdlib.com/\"><img src=\"../../img/d9bbbc949fa2f5449eb03a49337254ec.jpg\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东省图书馆\"></a>");
document.writeln("          </li>");
document.writeln("                    <li class=\"col-sm-2 p0\">");
document.writeln("            <a href=\"http://www.sdsysyjy.com/\"><img src=\"../../img/5606fd30d2ba9ac9c63c4b5498980213.png\" class=\"col-xs-10 col-sm-offset-1 p0 bor_cc\" alt=\"山东省艺术研究院\"></a>");
document.writeln("          </li>");
document.writeln("                     ");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <!-- 友情链接结束 -->");
document.writeln("    <!-- 底部开始 -->");
document.writeln("    <div id=\"footer\" class=\"bg_f5 hidden-xs clearfix col-xs-12 overflow\">");
document.writeln("      <div class=\"container col_67 p0\">");
document.writeln("        <div class=\"nav col-md-8 col-md-offset-2 hidden-xs text-center size14 p0\">");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-companyProfile.html\">公司简介</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-cooperInves.html\">合作招商</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-ourPartners.html\">合作伙伴</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-privacyState.html\">隐私声明</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-jobOppor.html\">人才招聘</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot- contactUs.html\">联系我们</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"../../html/footer/fot-siteMap.html\">网站地图</a>");
document.writeln("          <a class=\"bor_r_db\" href=\"\">友情链接</a>");
document.writeln("          <a href=\"\">帮助中心</a>");
document.writeln("        </div>");
document.writeln("        <div class=\"clearfix\"></div>");
document.writeln("        <div class=\"text-center mt10 size14 size12-xs\">Copyright 齐鲁艺票通网");
document.writeln("          <span>鲁ICP备13028754号-4</span>");
document.writeln("        </div>");
document.writeln("        <div class=\"text-center mt10 size14 size12-xs\">版权所有：<a href=\"http://www.sdwhcm.com.cn\" style=\"display:inline-block\">山东文化传媒有限公司</a> 市场开发部：0531-88116156</div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <!-- 底部结束 -->");
document.writeln("    <!-- 左侧悬浮导航开始 -->");
document.writeln("    <div class=\"leftNav clearfix\">");
document.writeln("      <ul class=\"hidden-xs text-center\">");
document.writeln("        <li>");
document.writeln("          <a href=\"#drama\" class=\"drama bg_ff bor_t_ea\">");
document.writeln("            <img src=\"../../img/nav_i1.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i1c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\"#concert\" class=\"concert bg_ff\">");
document.writeln("            <img src=\"../../img/nav_i2.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i2c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\"#dance\" class=\"dance bg_ff\">");
document.writeln("            <img src=\"../../img/nav_i3.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i3c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\"#quyi\" class=\"quyi bg_ff\">");
document.writeln("            <img src=\"../../img/nav_i4.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i4c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\"#sport\" class=\"sport bg_ff\">");
document.writeln("            <img src=\"../../img/nav_i5.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i5c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("          <a href=\"#childPlay\" class=\"childPlay bg_ff\">");
document.writeln("            <img src=\"../../img/nav_i6.png\" class=\"nav_ia\" alt=\"\">");
document.writeln("            <img src=\"../../img/nav_i6c.png\" class=\"nav_ib\" alt=\"\">");
document.writeln("          </a>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("    </div>");